### ISSUE TITLE
app is re-loading every time adal renews a token

### ISSUE THREAD

**Issue by riteshmeher** [benbaran/adal-angular4#28] opened 2017-12-11 10:27 UTC
we implemented this library in our app. However our app is getting reloaded during any http request. It is calling the acquiretoken method which is refreshing the entire app(js,css). This makes our app very slow.
any idea how to solve this in angular 2/4?
I can see there is a FAQ in https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs

**Comment by geerzo** [comment] 2018-08-01 01:15
Duplicate of #24

**Closed by geerzo** 2018-08-01 01:15 UTC
Labels: duplicate
