### ISSUE TITLE
Endpoint Token Response `ERROR Token renewal operation failed due to timeout.`

### ISSUE THREAD

**Issue by chase-swanson** [benbaran/adal-angular4#47] opened 2018-05-10 22:43 UTC
Struggling to configure ADAL with Angular app.  Believe struggles are configuration based not the library, but any help would be greatly appreciated.

Angular 6 and adal-angular4 v 3.01

I can login to the site fine, but when requesting a token for an endpoint, the console errors with `ERROR Token renewal operation failed due to timeout.`

When I look at the actual traffic, I actually am receiving a token in a response from AAD, but it is a 302 and the token is actually embedded in html

```HTML
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="http://localhost:4201/#access_token=eyJ0eXAiOiJKV<valid token>&amp;token_type=Bearer&amp;expires_in=3599&amp;state=<guid>%7chttps%3a%2f%2<Endpoint Site>&amp;session_state=<guid>">here</a>.</h2>
</body></html>
```

As before, the token in the HTML is a valid token for the endpoint, but the the response is not being handled correctly and adding the token to the cache and future requests.

Seems to keep looping and opening an `iframe` inside of another `iframe` inside another `iframe`, etc, etc.

Any help would be extremely helpful.

**Comment by benbaran** [comment] 2018-05-10 23:15
Hmmm. Not sure. What are you using for your configuration object? Fake example values are fine : )

**Comment by benbaran** [comment] 2018-05-10 23:32
I wonder if it is because you have multiple endpoints I have not tested that. I’ll give it a try tomorrow.

**Comment by chase-swanson** [comment] 2018-05-10 23:40
Thinking my issue is really in Azure AD setup, but not sure what I am missing.  Not sure if this will shed any light on it.

![frames](https://user-images.githubusercontent.com/11435869/39899452-cb98adf8-5470-11e8-8f0c-95de6cfa4032.png)

**Comment by AtomicBlom** [comment] 2018-05-11 06:19
I've been trying to get to the bottom of this as well, after enabling adal-angular logging, I've stumbled across this message:

```
> Logging = {
    level: 3,
    log: function (message) {
        console.log(message);
    },
    piiLoggingEnabled: false
};

Fri, 11 May 2018 06:08:27 GMT:1.0.17-VERBOSE: Expected state: 8e542d88-cad9-4d0f-b541-e2b923199923 startPage:http://localhost:4200/login/user-not-authenticated
VM709:4 Fri, 11 May 2018 06:08:27 GMT:1.0.17-INFO: Navigate url:https://login.microsoftonline.com/common/oauth2/authorize?response_type=id_token&client_id=49d5c7c6-a3f2-4956-ad63-8b62812fce88&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Flogin&state=8e542d88-cad9-4d0f-b541-e2b923199923&client-request-id=bb18128f-5eb2-44db-b7f6-0477222bdd6a&x-client-SKU=Js&x-client-Ver=1.0.17
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-VERBOSE: State: 8e542d88-cad9-4d0f-b541-e2b923199923
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-INFO: Returned from redirect url
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-INFO: State status:true; Request type:RENEW_TOKEN
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-INFO: State is right
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-INFO: Fragment has id token
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-VERBOSE: acquiring token interactive in progress
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-VERBOSE: renewing access_token
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-INFO: renewToken is called for resource:74ff7c99-2022-4548-b768-f94384e8af6d
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-INFO: Add adal frame to document:adalRenewFrame74ff7c99-2022-4548-b768-f94384e8af6d
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-VERBOSE: Renew token Expected state: 4be09eeb-e3c7-41a4-ac2a-1432362716b5|74ff7c99-2022-4548-b768-f94384e8af6d
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-INFO: Navigate url:https://login.microsoftonline.com/common/oauth2/authorize?response_type=token&client_id=49d5c7c6-a3f2-4956-ad63-8b62812fce88&resource=74ff7c99-2022-4548-b768-f94384e8af6d&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Flogin&state=4be09eeb-e3c7-41a4-ac2a-1432362716b5%7C74ff7c99-2022-4548-b768-f94384e8af6d&client-request-id=f0d588d9-b8c9-492f-9a39-3fe50a32fb4f&x-client-SKU=Js&x-client-Ver=1.0.17
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-VERBOSE: Set loading state to pending for: 74ff7c99-2022-4548-b768-f94384e8af6d
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-INFO: LoadFrame: adalRenewFrame74ff7c99-2022-4548-b768-f94384e8af6d
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-INFO: Closing popup window
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-INFO: Add adal frame to document:adalRenewFrame74ff7c99-2022-4548-b768-f94384e8af6d
VM709:4 Fri, 11 May 2018 06:08:28 GMT:1.0.17-INFO: LoadFrame: adalRenewFrame74ff7c99-2022-4548-b768-f94384e8af6d
VM709:4 Fri, 11 May 2018 06:08:31 GMT:1.0.17-INFO: Add adal frame to document:adalRenewFrame74ff7c99-2022-4548-b768-f94384e8af6d
core.js:3258 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
VM709:4 Fri, 11 May 2018 06:08:34 GMT:1.0.17-VERBOSE: Loading frame has timed out after: 6 seconds for resource 74ff7c99-2022-4548-b768-f94384e8af6d
VM709:4 Fri, 11 May 2018 06:08:34 GMT:1.0.17-ERROR: Error when acquiring token for resource: 74ff7c99-2022-4548-b768-f94384e8af6d
stack:
undefined
```

This appears to relate to an existing issue in the adal-angular repository from a week and a bit ago, but unanswered.
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/736

**Comment by rjwijnen** [comment] 2018-05-18 11:50
I am having the same problems. @benbaran  maybe you could set adal-angular version back to 1.0.15 till the problem is fixed?

**Comment by web265p3** [comment] 2018-05-22 09:55
Same issue here :-)

**Comment by stuarthallows** [comment] 2018-05-31 23:12
It look as if the underlying issue in the ADAL for JS library has just been resolved;
https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/760

**Comment by leonixyz** [comment] 2018-06-05 13:01
[this commit](https://github.com/benbaran/adal-angular4/commit/5d8c7435c05e3153d75b50c6cc02f4d23642dec8) modified the dependency with adal-angular.

This is the same error I experienced months ago, and i fixed it with my [pull request](https://github.com/benbaran/adal-angular4/pull/33), unfortunately @benbaran for some reason has changed it again

**Comment by peac3maker** [comment] 2018-06-10 20:48
I'm currently using this nasty workaround: 

Manually remove the adal-angular folder from your node_modules (not adal-angular4) 
Run npm install adal-angular@1.0.15 on your project
Manually change the dependency to adal-angular in the package.json of node_modules/adal-angular4 to version 1.0.15
Try again! Be aware that you will have to make sure that the version 1.0.17 is not installed again after you use npm install

**Comment by web265p3** [comment] 2018-06-13 12:56
I do it the same way. I also deploy my app with Visual Studio Teamservices, and here I cannot use the workaround. It would be awesome if @benbaran could change back to 1.0.15

**Comment by martinvillysson** [comment] 2018-06-21 09:13
While waiting for an official fix from @benbaran I forked the repo, rolled back adal-angular to 1.0.15, compiled the code and uploaded the built output to [https://github.com/martinvillysson/adal-angular4](https://github.com/martinvillysson/adal-angular4). We then use it in out package.json like this: `"adal-angular4": "martinvillysson/adal-angular4"`.

**Comment by j-turner28** [comment] 2018-06-28 09:47
@benbaran Can we please get a fix for this, even if it's just a short term fix like rolling back the version of adal-angular to 1.0.15?

**Comment by chase-swanson** [comment] 2018-06-28 17:20
@j-turner28 My guess is he is waiting for 1.0.18 to come out. They have already merged that code in, but have not released it yet.

I simply just brought @benbaran code into my application and cited his work and then I can control the adal-angular dependency myself.

**Comment by DanaEpp** [comment] 2018-07-01 22:18
Hmmm... @benbaran any update on when this will be fixed?

**Comment by benbaran** [comment] 2018-07-03 23:00
I have downgraded in the version released today. Sorry for the delay, this is a hobby project and I don’t always have time to make timely updates.

**Comment by rjwijnen** [comment] 2018-07-04 13:04
@benbaran i still get adal-angular 1.0.17 with the latest 3.0.4 version??

**Comment by benbaran** [comment] 2018-07-04 20:37
Yeah, I accidentally ran a npm update before I published out of habit. I will correct it tomorrow.

**Comment by rjwijnen** [comment] 2018-07-05 09:03
@benbaran would be great! 👍

**Comment by web265p3** [comment] 2018-07-05 10:40
Cant wait :)

**Comment by benbaran** [comment] 2018-07-06 00:13
It is updated, I think...

**Comment by geerzo** [comment] 2018-08-01 01:54
adal-angular has been reverted back to 1.0.15. There are other issues looking into fixing the issue with 1.0.17 so closing this one.

**Closed by geerzo** 2018-08-01 01:54 UTC

**Comment by shijinmk2006** [comment] 2020-04-15 10:32
Am facing the same issue while acquiring token. Using adal-angular4 : "4.0.12" .Still it generate the adal-angular:1.0.17 . How can i degrade to 1.0.15 at this time. While am using this Token timeout occurs eventually am not able to click on any links as i got unauthorized.In the token timeout there is a logic to set authenticated=false.

Any update on this?
