### ISSUE TITLE
ERROR Token renewal operation failed due to timeout angular 6

### ISSUE THREAD

**Issue by som-nitjsr** [benbaran/adal-angular4#43] opened 2018-05-08 06:55 UTC
I am getting this error while updated to angular6. it was working till angular 5  
this.adalService.acquireToken("00000003-0000-0000-c000-000000000000").subscribe(token => {

           console.log(token);

        });

**Comment by DanaEpp** [comment] 2018-07-01 22:19
Is this not related to https://github.com/benbaran/adal-angular4/issues/47? #47

**Comment by geerzo** [comment] 2018-08-01 02:18
Duplicate of #47

**Closed by geerzo** 2018-08-01 02:18 UTC
